[package]
name = "chip8"
version = "0.1.0"
authors = ["emlautarom1 <emlautarom1@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.8.3"
piston = "0.52.1"
piston2d-graphics = "0.39.0"
pistoncore-glutin_window = "0.68.0"
piston2d-opengl_graphics = "0.77.0"